[phases.setup]
nixPkgs = ['openjdk21']

[phases.build]
cmds = ['cd backend && ./mvnw package -DskipTests']

[start]
cmd = 'cd backend && java -jar target/*.jar'

[variables]
JAVA_HOME = "/nix/store/$(ls /nix/store | grep -m 1 openjdk-21)" 