[phases.setup]
nixPkgs = ['openjdk21', 'bash']

[phases.build]
cmds = ['cd backend && bash build.sh']

[start]
cmd = 'cd backend && java -jar target/*.jar'

[variables]
JAVA_HOME = "/nix/store/$(ls /nix/store | grep -m 1 openjdk-21)" 