[build]
builder = "DOCKERFILE"
dockerfilePath = ".railway/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
JAVA_HOME = "/nix/store/$(ls /nix/store | grep -m 1 openjdk-21)" 