[build]
builder = "nixpacks"
buildCommand = "cd backend && bash build.sh"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
JAVA_HOME = "/nix/store/$(ls /nix/store | grep -m 1 openjdk-21)" 